	soc u0 (
		.clk_clk                 (<connected-to-clk_clk>),                 //             clk.clk
		.keycode_export          (<connected-to-keycode_export>),          //         keycode.export
		.otg_hpi_address_export  (<connected-to-otg_hpi_address_export>),  // otg_hpi_address.export
		.otg_hpi_cs_export       (<connected-to-otg_hpi_cs_export>),       //      otg_hpi_cs.export
		.otg_hpi_data_in_port    (<connected-to-otg_hpi_data_in_port>),    //    otg_hpi_data.in_port
		.otg_hpi_data_out_port   (<connected-to-otg_hpi_data_out_port>),   //                .out_port
		.otg_hpi_r_export        (<connected-to-otg_hpi_r_export>),        //       otg_hpi_r.export
		.otg_hpi_reset_export    (<connected-to-otg_hpi_reset_export>),    //   otg_hpi_reset.export
		.otg_hpi_w_export        (<connected-to-otg_hpi_w_export>),        //       otg_hpi_w.export
		.reset_reset_n           (<connected-to-reset_reset_n>),           //           reset.reset_n
		.sdram_clk_clk           (<connected-to-sdram_clk_clk>),           //       sdram_clk.clk
		.sdram_wire_addr         (<connected-to-sdram_wire_addr>),         //      sdram_wire.addr
		.sdram_wire_ba           (<connected-to-sdram_wire_ba>),           //                .ba
		.sdram_wire_cas_n        (<connected-to-sdram_wire_cas_n>),        //                .cas_n
		.sdram_wire_cke          (<connected-to-sdram_wire_cke>),          //                .cke
		.sdram_wire_cs_n         (<connected-to-sdram_wire_cs_n>),         //                .cs_n
		.sdram_wire_dq           (<connected-to-sdram_wire_dq>),           //                .dq
		.sdram_wire_dqm          (<connected-to-sdram_wire_dqm>),          //                .dqm
		.sdram_wire_ras_n        (<connected-to-sdram_wire_ras_n>),        //                .ras_n
		.sdram_wire_we_n         (<connected-to-sdram_wire_we_n>),         //                .we_n
		.draw_control_re_ocm     (<connected-to-draw_control_re_ocm>),     //    draw_control.re_ocm
		.draw_control_writepixel (<connected-to-draw_control_writepixel>), //                .writepixel
		.draw_control_writex     (<connected-to-draw_control_writex>),     //                .writex
		.draw_control_writey     (<connected-to-draw_control_writey>),     //                .writey
		.draw_control_drawx      (<connected-to-draw_control_drawx>),      //                .drawx
		.draw_control_drawy      (<connected-to-draw_control_drawy>),      //                .drawy
		.draw_control_startp     (<connected-to-draw_control_startp>),     //                .startp
		.draw_control_endp       (<connected-to-draw_control_endp>),       //                .endp
		.draw_control_we         (<connected-to-draw_control_we>),         //                .we
		.draw_control_run        (<connected-to-draw_control_run>),        //                .run
		.vga_control_red         (<connected-to-vga_control_red>),         //     vga_control.red
		.vga_control_green       (<connected-to-vga_control_green>),       //                .green
		.vga_control_blue        (<connected-to-vga_control_blue>),        //                .blue
		.vga_control_blank       (<connected-to-vga_control_blank>),       //                .blank
		.vga_clk_pr_clk          (<connected-to-vga_clk_pr_clk>),          //      vga_clk_pr.clk
		.vga_clk_dc_clk          (<connected-to-vga_clk_dc_clk>),          //      vga_clk_dc.clk
		.conduit_startpoint      (<connected-to-conduit_startpoint>),      //         conduit.startpoint
		.conduit_endpoint        (<connected-to-conduit_endpoint>),        //                .endpoint
		.conduit_done            (<connected-to-conduit_done>),            //                .done
		.conduit_run             (<connected-to-conduit_run>)              //                .run
	);

